export default class authElement{
    element ={
        newUser_title: () => cy.get('.signup-form h2'),
        login_title: () => cy.get('.login-form h2'),
        userName: () => cy.get('[data-qa="signup-name"]'),
        userEmail: () => cy.get('[data-qa="signup-email"]'),
        loginEmail: () => cy.get('[data-qa="login-email"]'),
        loginPassword: () => cy.get('[data-qa="login-password"]'),
        signupBtn: () => cy.get('.signup-form button'),
        loginBtn: () => cy.get('.login-form button'),
        form_title: () => cy.get('.login-form h2'),
        genderTitle: () => cy.get('[type="radio"]'),
        userPass: () => cy.get('[data-qa="password"]'),
        day: () => cy.get('.col-xs-4>.selector [data-qa="days"]'),
        month: () => cy.get('.col-xs-4>.selector [data-qa="months"]'),
        year: () => cy.get('.col-xs-4>.selector [data-qa="years"]'),
        newsletter_checkbox: () => cy.get('[name="newsletter"]'),
        offers_checkbox: () => cy.get('[name="optin"]'),
        firstName: () => cy.get('#first_name'),
        lastName: () => cy.get('#last_name'),
        company: () => cy.get('#company'),
        address1: () => cy.get('#address1'),
        address2: () => cy.get('#address2'),
        country: () => cy.get('[data-qa="country"]'),
        state: () => cy.get('#state'),
        city: () => cy.get('#city'),
        zipcode: () => cy.get('#zipcode'),
        mobileNumber: () => cy.get('#mobile_number'),
        createAccountBtn: () => cy.get('button').contains('Create Account'),
        accountCreated_page: () => cy.get('.col-sm-9'),
        accountCreated_title: () => cy.get('.title'),
        continueBtn: () => cy.get('[data-qa="continue-button"]'),
        login_error_msg: () => cy.get('.login-form p'),
        signup_error_msg: () => cy.get('.signup-form p')

    }
}